remove micronaut-jackson-databind
without this dependency, the following error is observed:

```
    Caused by: java.lang.NoClassDefFoundError: io/micronaut/jackson/env/JsonPropertySourceLoader
```